add: Getting-Started 번역
fastify/fastify-korean pull request #23
Opened 2023-01-19 11:13 UTC by 6unpk

Getting-Started 번역 내용입니다. 모호한 번역이 조금 있어 코멘트로 남겨놓겠습니다~!

2023-01-19 11:17 UTC, 6unpk commented
코드내 주석 중 다음 원문을 어떻게 번역해야할지 난감하네요
```js
// Wrapping a plugin function with fastify-plugin exposes the decorators
// and hooks, declared inside the plugin to the parent scope.
```
저는 일단 'Fastify-plugin 을 사용해 플러그인 함수를 감싸면 데코레이터와 훅을 외부로 노출시킨다'까지는 의미 전달이 명확한데 뒤의 `declared inside the plugin to the parent scope.` 해당 부분을 정확히 뭐라 번역해야할지 감이 안잡히네요..

2023-01-25 00:49 UTC, anniemon commented
> 저는 일단 'Fastify-plugin 을 사용해 플러그인 함수를 감싸면 데코레이터와 훅을 외부로 노출시킨다'까지는 의미 전달이 명확한데 뒤의 declared inside the plugin to the parent scope. 해당 부분을 정확히 뭐라 번역해야할지 감이 안잡히네요..

`declared inside the plugin to the parent scope.`는 앞의 데코레이터와 훅을 수식하는 것으로 보이네요. 저라면 `fastify 플러그인으로 플러그인 함수를 감싸면, 플러그인 내부의 상위 스코프에 (선언된) 데코레이터와 훅을 노출합니다.` 정도로 번역할 것 같아요.😊

2023-01-27 11:20 UTC, 6unpk commented
> Collaborator

의견 감사합니다! 보다 명확하게 이해되었네요

2023-01-31 17:03 UTC, anniemon commented on docs/Guides/Getting-Started.md
> +본 문서는 Fastify 프레임워크의 특징을 쉽고 간단히 알아볼 수 있도록 하는데 초점을 맞췄습니다. 본 문서는 쉽고 간단한 소개문이며 동시에 다른 문서들의 진입점 역할을 합니다.
`with examples`까지 살려서 번역해보면 어떨까요.

2023-01-31 17:03 UTC, anniemon commented on docs/Guides/Getting-Started.md
> +`async/await` 사용을 더 선호 하시나요? Fastify는 당연하게도 이를 지원합니다. <!-- https://web-front-end.tistory.com/84 -->
이 티스토리 링크는 빼는 게 좋을 듯합니다.

2023-02-01 03:33 UTC, 6unpk commented on docs/Guides/Getting-Started.md
> +`async/await` 사용을 더 선호 하시나요? Fastify는 당연하게도 이를 지원합니다. <!-- https://web-front-end.tistory.com/84 -->
넵 구어체 번역에 대한 참조 링크로 남겨두었는데 번역상 문제가 없다면 삭제하도록 하겠습니다~!

2023-02-02 16:09 UTC, anniemon commented
// Server is now listening on ${address}
이 부분도 번역하면 좋을 것 같습니다😊

2023-02-02 16:11 UTC, anniemon commented on docs/Guides/Getting-Started.md
> +`async/await` 사용을 더 선호 하시나요? Fastify는 당연하게도 이를 지원합니다. <!-- https://web-front-end.tistory.com/84 -->
넵.. 문제는 없지만 `당연하게도`는 의역 느낌이 좀 있긴 하네요. `기본으로` 지원한다... 정도의 번역도 괜찮을 듯합니다. 큰 차이는 아닌 것 같긴 해요.

2023-02-02 16:11 UTC, anniemon commented on docs/Guides/Getting-Started.md
> +그러나 불운하게도, 이보다 복잡한 어플리케이션을 만드려면 훨씬 많은 코드를 작성해야합니다.
`불운하게도` 보다 `안타깝게도` 어떠세요? 어감이 조금...ㅎㅎㅎ

2023-02-02 16:11 UTC, anniemon commented on docs/Guides/Getting-Started.md
> +Fastify는 이와 같은 문제 이외에도 더 많은 문제들을 쉽게 해결할 수 있는 방법(platform)을 제공합니다!
플랫폼은 개인적으로 그냥 `플랫폼`으로 해도 좋을 것 같아요.

2023-02-02 16:11 UTC, anniemon commented on docs/Guides/Getting-Started.md
> +> ## 비고
`비고` 보다는 `주의`를 권장하고 있습니다. (wiki 참고해주세요!)

2023-02-02 16:11 UTC, anniemon commented on docs/Guides/Getting-Started.md
> +> 위에서 보인 예시에서, 로컬호스트인 `127.0.0.1` 만 접속을 허용하도록 기본 설정이 되어 있습니다.
`위의 예와 뒤따르는 이 글의 다른 예시들에서도~`

2023-02-02 16:11 UTC, anniemon commented on docs/Guides/Getting-Started.md
> +> 운영체제에서 IPv6를 지원하는 경우 `::`는 모든 IPv6 주소의 접속을 받아들일 수 있으며, 이는 IPv4 주소 역시 마찬가지입니다.
` ::는 모든 IPv6 주소에서 연결을 수락합니다. 운영 체제에서 지원하는 경우, IPv4 주소 연결 역시 수락합니다.` 이렇게 되어야 하겠네요.

2023-02-02 16:11 UTC, anniemon commented on docs/Guides/Getting-Started.md
> +> `::` 로 설정하면 쉽게 외부로 공개할 수 있습니다.
`설정하는 것이 애플리케이션을 외부에 노출하는 가장 쉬운 방법입니다.` 정도로 번역해야겠어요.

2023-02-02 16:11 UTC, anniemon commented on docs/Guides/Getting-Started.md
> +> `::` 로 설정하면 쉽게 외부로 공개할 수 있습니다.
그리고 `컨테이너 포트`가 아닐 수도 있는 듯해서.. (IPv4, IPv6의 경우) 이 주어를 빼고 거의 직역하여  `0.0.0.0 또는 ::를 사용하는 것이 애플리케이션을~` 정도로 하면 어떨까요?

2023-02-02 16:11 UTC, anniemon commented on docs/Guides/Getting-Started.md
> +자바스크립트에서 모든것이 객체로 취급되듯이, Fastify에서는 모든 것들이 Plugin으로 다뤄질 수 있습니다.
객체로 취급되는 것이 아니라 객체예요! ㅎㅎㅎ(프로토타입 체인을 거슬러 올라가면 Object가 나오는 걸로 알고 있습니다..)

2023-02-02 16:11 UTC, anniemon commented on docs/Guides/Getting-Started.md
> +자바스크립트에서 모든것이 객체로 취급되듯이, Fastify에서는 모든 것들이 Plugin으로 다뤄질 수 있습니다.
`Plugin으로 다뤄`진다는 표현은 다소 초월 번역이에요.
`자바스크립트에서 모든 것이 객체이듯이, Fastify에서는 모든 것이 plugin입니다.` 정도가 적당해보여요.

2023-02-02 16:29 UTC, anniemon commented
전체적으로 부산대 맞춤법 검사기 한 번 돌려보시는 거 추천드립니다😊

2023-02-02 16:30 UTC, anniemon commented on docs/Guides/Getting-Started.md
> +데이터 저장을 다루기 위해 데이터베이스 연길이 필요한 시나리오를 고려해봅시다. 데이터베이스 연결은 서버가 연결을 받아들이기 전에 사용이 가능해야만 합니다.
`연길` -> `연결`

2023-02-02 16:30 UTC, anniemon commented on docs/Guides/Getting-Started.md
> +데이터 저장을 다루기 위해 데이터베이스 연길이 필요한 시나리오를 고려해봅시다. 데이터베이스 연결은 서버가 연결을 받아들이기 전에 사용이 가능해야만 합니다.
`서버가 연결되기 전에 데이터베이스 연결을 사용할 수 있어야 합니다.` 이건 어떤가요??

2023-02-03 04:50 UTC, 6unpk commented on docs/Guides/Getting-Started.md
> +> ## 비고
wiki가 있었군요 감사합니다!

2023-02-05 09:04 UTC, 6unpk commented on docs/Guides/Getting-Started.md
> +그러나 불운하게도, 이보다 복잡한 어플리케이션을 만드려면 훨씬 많은 코드를 작성해야합니다.
넵 다시보니 `안타깝게도`가 조금더 자연스러울 것 같네요 :)

2023-02-05 09:09 UTC, 6unpk commented on docs/Guides/Getting-Started.md
> +> `::` 로 설정하면 쉽게 외부로 공개할 수 있습니다.
앗 그렇네요 지금보니 왜 저렇게 번역했는지...

2023-02-05 09:24 UTC, 6unpk commented on docs/Guides/Getting-Started.md
> +자바스크립트에서 모든것이 객체로 취급되듯이, Fastify에서는 모든 것들이 Plugin으로 다뤄질 수 있습니다.
> 객체로 취급되는 것이 아니라 객체예요! ㅎㅎㅎ(프로토타입 체인을 거슬러 올라가면 Object가 나오는 걸로 알고 있습니다..)

넵 그럴 의도로 번역한 건 아닌데, 의미가 잘못 전달된 것 같네요.. 감사합니다!

2023-02-05 09:27 UTC, 6unpk commented on docs/Guides/Getting-Started.md
> +데이터 저장을 다루기 위해 데이터베이스 연길이 필요한 시나리오를 고려해봅시다. 데이터베이스 연결은 서버가 연결을 받아들이기 전에 사용이 가능해야만 합니다.
> `서버가 연결되기 전에 데이터베이스 연결을 사용할 수 있어야 합니다.` 이건 어떤가요??

넵 이게 조금더 자연스럽네요 감사합니다!

2023-02-05 09:48 UTC, 6unpk commented on docs/Guides/Getting-Started.md
> +> 운영체제에서 IPv6를 지원하는 경우 `::`는 모든 IPv6 주소의 접속을 받아들일 수 있으며, 이는 IPv4 주소 역시 마찬가지입니다.
`if the operating system supports it`에서 it이 앞의 '::' 표기법을 의미하는 것 같은데 이 의미를 살려서 넣는건 어떻게 생각하시나요? 그래서 원래 제가 번역한 부분에서도  '운영체제에서 IPv6를 지원하는 경우'라고 번역하긴 했습니다~!

2023-02-05 11:54 UTC, anniemon commented on docs/Guides/Getting-Started.md
> +> 운영체제에서 IPv6를 지원하는 경우 `::`는 모든 IPv6 주소의 접속을 받아들일 수 있으며, 이는 IPv4 주소 역시 마찬가지입니다.
'::' 표기는 기본적으로 모든 IPv6 주소에서 연결을 수락하고, IPv4는 운영 체제에서 지원하는 경우에만 연결을 수락한다는 의미로 저는 이해했어요~ (앞의 IPv6의 경우는 운영체제 이야기는 아예 없어서..)

2023-02-05 12:11 UTC, anniemon commented on docs/Guides/Getting-Started.md
> +첫번쨰로, `fastify-plugin` 와 `@fastify/mongodb`를 설치합니다:
`첫번째`

2023-02-05 12:11 UTC, anniemon commented on docs/Guides/Getting-Started.md
> +지금까지 새로운 개념들을 소개하기까지 우리가 무엇을 했었는지 한 번 되돌아봅시다.
이 문장은 아직 새로운 개념을 소개하지 않은 것처럼 읽힐 수 있겠어요. 지금까지 새로운 개념을 소개했다는 것을 알릴 표현이 필요합니다.

2023-02-05 12:11 UTC, anniemon commented on docs/Guides/Getting-Started.md
> +하나의 플러그인을 가져오면 그 다음 플러그인을 가져옵니다. 이러한 방식으로 데이터베이스 커넥터를 가장 먼저 등록한 후
`이런 방식으로 우리는 첫 번째 플러그인에 데이터베이스 커넥터를 등록하고 두 번째 플러그인에서 사용할 수 있습니다.`가 더 적합할 것 같습니다.

2023-02-05 13:17 UTC, anniemon commented on docs/Guides/Getting-Started.md
> +더 자세히 알기위해서는 [플러그인을 여행하는 히치하이커를 위한 안내서](./Plugins-Guide.md) 를 읽어보세요.
`알기 위해서는` (띄어쓰기) 😊

2023-02-05 13:17 UTC, anniemon commented on docs/Guides/Getting-Started.md
> +어플리케이션의 일관적이고 예측가능한 행동을 보장하기 위해, 다음과 같이 코드를 순차적으로 불러오는 걸 걍력히 권장합니다:
`강력히`

2023-02-05 13:17 UTC, anniemon commented on docs/Guides/Getting-Started.md
> +만약 플러그인을 라우트의 하위 집합만으로 플러그인을 등록하기를 원한다면, 위의 구조를 그대로 복제하면 그만입니다.
`플러그인을`이 두 번 나오는데 앞의 것은 삭제해도 무방하겠어요!

2023-02-05 13:17 UTC, anniemon commented on docs/Guides/Getting-Started.md
> +라우트에서 데이터 검증에 대해 확인해보기 위해 에제를 한 번 살펴봅시다:
`에제를` -> `예제를`

2023-02-05 13:17 UTC, anniemon commented on docs/Guides/Getting-Started.md
> +더 많은 것을 배우려면 [검증과 직렬화](../Reference/Validation-and-Serialization.md)을 읽어보세요.
`을` -> `를`

2023-02-05 13:17 UTC, anniemon commented on docs/Guides/Getting-Started.md
> +Fastify는 JSON에 대한 지원을 아주 잘 지원합니다. 그리고 JSON 본문을 파싱하고 JSON 출력을 직렬화 하는데 있어 최적화가 아주 잘 되어있습니다.
`Fastify는 JSON을 최고 수준으로 지원합니다.` 는 어떨까요?

2023-02-05 13:17 UTC, anniemon commented on docs/Guides/Getting-Started.md
> +또한 잠재적인 중요 데이터의 누락으로부터 도와주기도 합니다. Fastify는 현재 스키마에 보이는 데이터에 대해서만 직렬화를 하기 때문입니다.
`응답 스키마`에 대해서만 직렬화를 한다고 해야 정확할 거 같아요.

2023-02-05 13:17 UTC, anniemon commented on docs/Guides/Getting-Started.md
> +Fastify는 `'application/json'`과 `'text/plain'` 요청 페이로드를 기본적으로 파싱하미,
`파싱하미` -> `파싱하며`

2023-02-05 13:17 UTC, anniemon commented on docs/Guides/Getting-Started.md
> +Fastif의 기본 파싱 기능과 다른 콘턴츠 타입을 지원하려면 어떻게 해야하는지 자세히 알아보려면 [Content-Type Parser](../Reference/ContentTypeParser.md) 을 읽어보세요.
`콘턴츠` -> `콘텐츠`

2023-02-05 13:17 UTC, anniemon commented on docs/Guides/Getting-Started.md
> +Fastify는 테스팅 프레임워크를 제공하지 않고 있지만, 기능과 Fastify 아키텍처에 대해 테스트를 작성하는 것을 추천합니다.
`but we~`부터는 `우리는 여러분이 Fastify의 기능과 아키텍처를 이용하는 테스트를 작성하는 방법을 추천합니다.`정도가 좋을 것 같아요. 어떻게 생각하시나요?

2023-02-05 13:17 UTC, anniemon commented on docs/Guides/Getting-Started.md
> +### CLI 에세 서버 실행하기
`에세` -> `에서`

2023-02-05 13:17 UTC, anniemon commented on docs/Guides/Getting-Started.md
> +그런뒤 서버를 다음과 같이 실행합니다:
`그런 뒤` (띄어쓰기)

2023-02-05 13:19 UTC, anniemon requested changes

2023-02-05 13:19 UTC, anniemon commented on docs/Guides/Getting-Started.md
> +by [@delvedor](https://github.com/delvedor)
이 부분도 번역해주세요~ 사실상 `Take your HTTP server to ludicrous
speed`, `What if I told you that HTTP can be
fast` 요 두 문장만 하는 거나 다름없군요..!

2023-02-08 02:46 UTC, 6unpk commented on docs/Guides/Getting-Started.md
> +> 운영체제에서 IPv6를 지원하는 경우 `::`는 모든 IPv6 주소의 접속을 받아들일 수 있으며, 이는 IPv4 주소 역시 마찬가지입니다.
음 네 생각해보니 말씀주신 맥락에서 봤을때 제안해주신 내용도 맞는 것 같네요 감사합니다!

2023-02-08 02:48 UTC, 6unpk commented on docs/Guides/Getting-Started.md
> +하나의 플러그인을 가져오면 그 다음 플러그인을 가져옵니다. 이러한 방식으로 데이터베이스 커넥터를 가장 먼저 등록한 후
넵 의견 감사합니다!

2023-02-08 02:54 UTC, 6unpk commented on docs/Guides/Getting-Started.md
> +Fastify는 JSON에 대한 지원을 아주 잘 지원합니다. 그리고 JSON 본문을 파싱하고 JSON 출력을 직렬화 하는데 있어 최적화가 아주 잘 되어있습니다.
first-class 의 의미를 살리려면 그게 더 맞을 것 같네요 감사합니다~!

2023-02-08 04:54 UTC, 6unpk commented on docs/Guides/Getting-Started.md
> +Fastify는 테스팅 프레임워크를 제공하지 않고 있지만, 기능과 Fastify 아키텍처에 대해 테스트를 작성하는 것을 추천합니다.
넵 제안주신 번역이 더 적절한 것 같아요 감사합니다!

2023-02-08 05:05 UTC, 6unpk commented on docs/Guides/Getting-Started.md
> +지금까지 새로운 개념들을 소개하기까지 우리가 무엇을 했었는지 한 번 되돌아봅시다.
의견 감사합니다 `지금까지 새로운 개념을 소개하면서 우리가 무엇을 했었는지 한 번 되돌아봅시다.` 이런식으로 바꿔보겠습니다!

2023-02-08 05:23 UTC, 6unpk commented
생각보다 오탈자가 상당히 많았네요;; 다음 부터는 셀프 리뷰를 조금더 철저히 하고 PR 올리도록 하곘습니다. 🙇

2023-02-12 14:18 UTC, anniemon commented on docs/Guides/Getting-Started.md
> +> `::`를 사용한느 것이 애플리케이션을 쉽게 외부로 공개할 수 있습니다.
`사용한느` -> `사용하는`

2023-02-12 14:24 UTC, anniemon commented
@6unpk 일단 초벌 번역은 충분히 해주신 듯하니, 윤문은 + 간단한 교정은 제가 해보도록 할게요!
기여해주셔서 너무나 감사합니다🙇🏻‍♀️

2023-02-12 14:29 UTC, anniemon commented on docs/Guides/Getting-Started.md
> +> `::`를 사용한느 것이 애플리케이션을 쉽게 외부로 공개할 수 있습니다.
```suggestion
> `::`를 사용하는 것이 애플리케이션을 쉽게 외부로 공개할 수 있는 방법입니다.
```

2023-02-12 14:30 UTC, anniemon approved these changes

2023-02-12 14:36 UTC, anniemon commented on docs/Guides/Getting-Started.md
> +또한 잠재배적인 중요 데이터의 누락으로부터 도와주기도 합니다. Fastify는 현재 스키마에 보이는 데이터에 대해서만 직렬화를 하기 때문입니다.
```suggestion
또한 잠재적인 중요 데이터의 누락으로부터 도와주기도 합니다. Fastify는 현재 응답 스키마에 보이는 데이터에 대해서만 직렬화를 하기 때문입니다.
```

2023-02-12 14:38 UTC, anniemon commented on docs/Guides/Getting-Started.md
> +Fastify는 JSON을 최고 수준으로 지원합니다. 그리고 JSON 본문을 파싱하고 JSON 출력을 직렬화하는데 있어 최적화가 아주 잘 되어있습니다.
```suggestion
Fastify는 JSON을 최고 수준으로 지원합니다. 그리고 JSON 본문을 파싱하고 JSON 출력을 직렬화하는 데 있어 최적화가 아주 잘 되어있습니다.
```

2023-02-18 16:37 UTC, anniemon commented on docs/Guides/Getting-Started.md
> +> `::`를 사용한느 것이 애플리케이션을 쉽게 외부로 공개할 수 있습니다.
@6unpk 제가 커밋하였습니다🙏🏻

2023-02-18 16:37 UTC, merged

2023-02-20 08:32 UTC, 6unpk commented
> @6unpk 일단 초벌 번역은 충분히 해주신 듯하니, 윤문은 + 간단한 교정은 제가 해보도록 할게요! 기여해주셔서 너무나 감사합니다🙇🏻‍♀️

넵 꼼꼼한 검수 감사합니다! :)